# -*- coding: utf-8 -*-
# """
# Extract image,Table,text from Document | Multimodal Summrizer.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1oa39-Tj5gRhYZBbs9wi0yQso5NrZ-U15

# # Realtime multimodal Usecase | Extract Image,Table,Text from Docoument | Multimodal Summrizer
# """

import pytesseract
import unstructured_pytesseract
import os

# If Tesseract is not in your PATH, uncomment and set the line below:
tesseract_bin = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
pytesseract.pytesseract.tesseract_cmd = tesseract_bin
unstructured_pytesseract.pytesseract.tesseract_cmd = tesseract_bin
os.environ['PATH'] += r';C:\Program Files\Tesseract-OCR'

poppler_path = r"C:\Users\nikhi\OneDrive\Desktop\Release-25.12.0-0\poppler-25.12.0\Library\bin"

# Commenting out Jupyter/Colab style commands to avoid SyntaxErrors in plain Python
# ! pip install "unstructured[all-docs]" pillow pydantic lxml matplotlib
# !sudo apt-get update
# !sudo apt-get install poppler-utils
# !sudo apt-get install libleptonica-dev tesseract-ocr libtesseract-dev python3-pil tesseract-ocr-eng tesseract-ocr-script-latn
# !pip install unstructured-pytesseract
# # !pip install tesseract-ocr  # Not needed on Windows
# !pip install langchain_core
# !pip install langchain
# !pip install langchain_community

# unstructured is a open source library
from unstructured.partition.pdf import partition_pdf

#this class is responsible for extracting information
raw_pdf_elements = partition_pdf(
    filename=r"c:\Users\nikhi\OneDrive\Desktop\Multi_modal_RAG\data\Cji.pdf",
    strategy="hi_res",
    extract_image_in_pdf=True,
    extract_image_block_types=["Image", "Table"],
    extract_image_block_to_payload=False,
    extract_image_block_output_dir="extracted_data",
    poppler_path=poppler_path
)

# from google.colab import drive
# drive.mount('/content/drive')

# raw_pdf_elements

#collect these items seperately
Header=[]
Footer=[]
Title=[]
NarrativeText=[]
Text=[]
ListItem=[]
for element in raw_pdf_elements:
  if "unstructured.documents.elements.Header" in str(type(element)):
            Header.append(str(element))
  elif "unstructured.documents.elements.Footer" in str(type(element)):
            Footer.append(str(element))
  elif "unstructured.documents.elements.Title" in str(type(element)):
            Title.append(str(element))
  elif "unstructured.documents.elements.NarrativeText" in str(type(element)):
            NarrativeText.append(str(element))
  elif "unstructured.documents.elements.Text" in str(type(element)):
            Text.append(str(element))
  elif "unstructured.documents.elements.ListItem" in str(type(element)):
            ListItem.append(str(element))

# NarrativeText

# ListItem

img=[]
for element in raw_pdf_elements:
  if "unstructured.documents.elements.Image" in str(type(element)):
            img.append(str(element))

tab=[]
for element in raw_pdf_elements:
  if "unstructured.documents.elements.Table" in str(type(element)):
            tab.append(str(element))

# tab

raw_pdf_elements2 = partition_pdf(
    filename=r"c:\Users\nikhi\OneDrive\Desktop\Multi_modal_RAG\data2\Retrieval-Augmented Generation for NLP.pdf",
    strategy="hi_res",
    extract_image_in_pdf=True,
    extract_image_block_types=["Image", "Table"],
    extract_image_block_to_payload=False,
    extract_image_block_output_dir="extracted_data2",
    poppler_path=poppler_path
)

# raw_pdf_elements2

img=[]
for element in raw_pdf_elements2:
  if "unstructured.documents.elements.Image" in str(type(element)):
            img.append(str(element))

len(img)

Tab=[]
for element in raw_pdf_elements2:
  if "unstructured.documents.elements.Table" in str(type(element)):
            Tab.append(str(element))

Tab[0] #tabular data extracted from table

NarrativeText=[]
for element in raw_pdf_elements2:
  if "unstructured.documents.elements.NarrativeText" in str(type(element)):
    NarrativeText.append(str(element))

ListItem=[]
for element in raw_pdf_elements2:
  if "unstructured.documents.elements.ListItem" in str(type(element)):
    ListItem.append(str(element))

# !pip install langchain-google-genai

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

"""
> **Table** summary




"""

# Prompt
prompt_text = """You are an assistant tasked with summarizing tables for retrieval. \
    These summaries will be embedded and used to retrieve the raw table elements. \
    Give a concise summary of the table that is well optimized for retrieval. Table:{element} """

prompt = ChatPromptTemplate.from_template(prompt_text)

import os
# from google.colab import userdata

# Fetch your Gemini API key stored in Colab's secret manager
# GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
GOOGLE_API_KEY = 'AIzaSyCpJogWwZX7en-xM9pKXNnT6IAfvot_Ku4' # Hardcoded API key

# Set the key as an environment variable so all libraries can access it
os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY or ""

print("Google API key set successfully!")

from langchain_google_genai import ChatGoogleGenerativeAI

model = ChatGoogleGenerativeAI(model="Gemini 2.5 Pro")

summarize_chain = {"element":lambda x: x} | prompt| model | StrOutputParser()

table_summaries = []

table_summaries=summarize_chain.batch(Tab,{"max_concurrency": 5})

Tab[0]

"""recalling summary of table [0]"""

table_summaries[0]

import base64 #Base64 is a group of similar binary-to-text encoding schemes that represent binary data in an ASCII string format
import os
from langchain_core.messages import HumanMessage

"""Image Encoding Method"""

def encode_image(image_path):
  """Getting the base64 string"""
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode("utf-8")

"""Image summary method"""

from langchain_core.messages import HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI


def image_summarize(img_base64, prompt):
    """Make image summary"""
    chat = ChatGoogleGenerativeAI(model="gemini-2.5-flash", max_tokens=1024)

    msg = chat.invoke(
        [ # Wrap the HumanMessage in a list
            HumanMessage(
                content=[
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{img_base64}"},
                    },
                ]
            )
        ]
    )
    return msg.content

"""img summary generation method"""

import base64 #Base64 is a group of similar binary-to-text encoding schemes that represent binary data in an ASCII string format
import os
from langchain_core.messages import HumanMessage

def encode_image(image_path):
  """Getting the base64 string"""
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode("utf-8")

def generate_img_summaries(path):
  """
  Generate summaries and base64 encoded strings for images
  path: Path to list of .jpg files extracted by Unstructured
  """

  #store base64 encoded images
  img_base64_list = []

  #store image summaries
  image_summaries = []

  # Prompt
  prompt = """You are an assistant tasked with summarizing images for retrieval. \
    These summaries will be embedded and used to retrieve the raw image. \
    Give a concise summary of the image that is well optimized for retrieval."""

  # Apply to images
  for img_file in sorted(os.listdir(path)):
    if img_file.endswith(".jpg"):
      img_path = os.path.join(path, img_file)
      base64_image = encode_image(img_path)
      img_base64_list.append(base64_image)
      image_summaries.append(image_summarize(base64_image, prompt)) # Pass the prompt to image_summary

  return img_base64_list, image_summaries

fpath="extracted_data2/"

# Image summaries
img_base64_list, image_summaries = generate_img_summaries(fpath)

image_summaries[0]

"""# Text summary"""

# Prompt
prompt_text = """You are an assistant tasked with summarizing text for retrieval. \
    These summaries will be embedded and used to retrieve the raw text elements. \
    Give a concise summary of the table or text that is well optimized for retrieval.text: {element} """

prompt = ChatPromptTemplate.from_template(prompt_text)

#text summary chain
model = ChatGoogleGenerativeAI(temperature=0, model="gemini-3.1-flash-lite")
summarize_chain = {"element":lambda x: x} | prompt| model | StrOutputParser()

from IPython.utils import text
#initialize empty summaries

text_summaries = []

text_summaries = summarize_chain.batch(Text, {"max_concurrency": 2})

text_summaries[0]

# ------------------------------------------------------------------
# Build Retriever  (logic lives in retriever.py)
# ------------------------------------------------------------------
from retriever import build_vectorstore, create_multi_vector_retriever

vectorstore = build_vectorstore()

retriever_multi_vector_img = create_multi_vector_retriever(
    vectorstore,
    text_summaries,  Text,
    table_summaries, Tab,
    image_summaries, img_base64_list,
)
