# -*- coding: utf-8 -*-
"""Multimodal_RAG2.0_using_llamaIndex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18beO25kepP6jck5GxnD-W9s40zLNVZH6
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install llama-index-vector-stores-lancedb
# %pip install llama-index-llms-google
# %pip install llama-index-embeddings-clip
# %pip install git+https://github.com/openai/CLIP.git
# !pip install llama-index-readers-file

# Commented out IPython magic to ensure Python compatibility.
# %pip install llama_index
# %pip install -U openai-whisper

# Commented out IPython magic to ensure Python compatibility.
# %pip install lancedb
# %pip install moviepy
# %pip install pydub
# %pip install SpeechRecognition
# %pip install ffmpeg-python
# %pip install soundfile
# %pip install torch torchvision
# %pip install matplotlib scikit-image
# %pip install ftfy regex tqdm

import os
os.system("apt-get install ffmpeg -y")

""">***Different_Python_lib_we_installed***

ffmpeg-library enables you to use FFmpeg in Python to manipulate various media files for different purposes like building comprehensive multimedia applications, preprocessing media files.

MoviePy is a Python library for video editing, enabling cutting, concatenations, title insertions, video compositing, and effects like animations or color grading.

Pytube is a Python library used for downloading videos from YouTube. It supports downloading in various formats, resolutions, and also direct audio extraction.

Pydub is a Python library for audio manipulation, enabling easy loading, editing, and exporting of audio files in various formats with minimal code.

The SpeechRecognition library in Python allows you to convert spoken language into text using various engines and APIs, such as Google Speech Recognition, IBM Speech to Text, etc.

SoundFile is a Python library for reading from and writing to audio files, supporting many formats through the libsndfile library, ideal for high-quality audio processing.

FTFY (Fix Text For You) is a Python library that fixes broken Unicode text and mojibake (garbled text due to encoding issues), making text legible again.

OpenAI Whisper is a robust, multilingual speech recognition model developed by OpenAI. It converts speech into text and supports various languages with high accuracy.

pprint is a Python module that provides a capability to "pretty-print" complex data structures in a well-formatted and more readable way than the basic print function.
"""

from moviepy.editor import VideoFileClip
from pathlib import Path
import speech_recognition as sr
from pprint import pprint
from PIL import Image
import matplotlib.pyplot as plt

"""***Integration_of_Google_API***"""

import os
import google.generativeai as genai

# Replace this with your new API key
os.environ["GOOGLE_API_KEY"] = os.environ.get("GOOGLE_API_KEY", "YOUR_API_KEY_HERE")

# Configure Gemini with the new key
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

print("New API key configured successfully!")

import os
print(os.getcwd())

"""***Video_URL_to_Update***"""

video_url="https://youtu.be/SalTNixtbh4?si=R4WqcJBT8Zed_76q"

output_video_path = "/content/video_data/"

# from the video i am going to collect images,audio,text
output_folder = "/content/mixed_data/"
output_audio_path = "/content/mixed_data/output_audio.wav"

# !mkdir mixed_data

filepath=output_video_path + "input_vid.mp4"
print(filepath)

# !pip install yt-dlp

"""DOWNLOADING VIDEO"""

import yt_dlp

def download_video(url, output_path):
    """
    Downloads a YouTube video and returns its metadata using yt-dlp.
    """
    # Define the options for yt-dlp
    ydl_opts = {
        'outtmpl': f'{output_path}/input_vid.mp4', # Specifies the save location and filename
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', # Gets the best quality
        'quiet': True, # Prevents yt-dlp from printing too much to the console
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            # Extract video information without downloading yet
            info_dict = ydl.extract_info(url, download=False)

            # Prepare the metadata dictionary
            metadata = {
                "Author": info_dict.get('uploader', 'N/A'),
                "Title": info_dict.get('title', 'N/A'),
                "Views": info_dict.get('view_count', 0)
            }

            # Now, trigger the actual download
            ydl.download([url])

            return metadata

    except Exception as e:
        print(f"An error occurred during download: {e}")
        return None

from moviepy.editor import VideoFileClip
def video_to_images(video_path,output_folder):
  clip=VideoFileClip(video_path)
  clip.write_images_sequence(
      os.path.join(output_folder,"frame%04d.png"),fps=0.2
  )

def video_to_audio(video_path,output_audio_path):
  clip=VideoFileClip(video_path)
  audio=clip.audio
  audio.write_audiofile(output_audio_path)

def audio_to_text(audio_path):
  recognizer=sr.Recognizer()
  audio=sr.AudioFile(audio_path)

  with audio as source:
    audio_data=recognizer.record(source)

    try:

      #recognize the speech
      text = recognizer.recognize_whisper(audio_data)

    except sr.UnknownValueError:
      print("Speech recognition could not understand the audio.")
  return text

video_url

output_video_path

metadata_vid = download_video(video_url, output_video_path)

metadata_vid

video_to_images(filepath,output_folder)

filepath

output_audio_path

video_to_audio(filepath,output_audio_path)

text_data=audio_to_text(output_audio_path)

text_data

with open(output_folder + "output_text.txt", "w") as file:
        file.write(text_data)
print("Text data saved to file")
file.close()

os.remove(output_audio_path)
print("Audio file removed")

#process the video
#image
#text

from llama_index.core.indices import MultiModalVectorStoreIndex
from llama_index.core import SimpleDirectoryReader
from llama_index.core import StorageContext

from llama_index.vector_stores.lancedb import LanceDBVectorStore

text_store = LanceDBVectorStore(uri="lancedb", table_name="text_collection")
image_store = LanceDBVectorStore(uri="lancedb", table_name="image_collection")

storage_context=StorageContext.from_defaults(vector_store=text_store,image_store=image_store)

output_folder

documents=SimpleDirectoryReader(output_folder).load_data()

"""EMbedding **happening**"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install llama-index-embeddings-huggingface

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

# set an embedding model
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

index = MultiModalVectorStoreIndex.from_documents(documents,storage_context=storage_context)

# Create a retriever engine from the multimodal index that fetches:
# - the top 1 most similar text result (similarity_top_k=1)
# - and the top 3 most similar image results (image_similarity_top_k=3)

retriever_engine=index.as_retriever(similariy_top_k=1, image_similarity_top_k=3)

# Import utility function to display source nodes in Jupyter/Colab notebooks.
# Useful for visually inspecting the source data behind LlamaIndex responses.
# Import the ImageNode schema class.
# This represents an image as a node in the LlamaIndex knowledge graph or index,
# enabling the index to handle multimodal data (images alongside text).

from llama_index.core.response.notebook_utils import display_source_node
from llama_index.core.schema import ImageNode

#method to retrieve information
def retrieve(retriever_engine, query_str):
    retrieval_results = retriever_engine.retrieve(query_str)

#seggeragating image and text
    retrieved_image = []
    retrieved_text = []

    #collect the images
    for res_node in retrieval_results:
        if isinstance(res_node.node, ImageNode):
            retrieved_image.append(res_node.node.metadata["file_path"])

            #collect the text
        else:
            display_source_node(res_node, source_length=200)
            retrieved_text.append(res_node.text)

    return retrieved_image, retrieved_text

"""***Here is the query***"""

query="what is this game is  , who is vegeta? ."

img,text=retrieve(retriever_engine, query)

#code to visualize the image path
import matplotlib.pyplot as plt
def plot_images(images_path):
  images_shown = 0
  plt.figure(figsize=(16, 9))
  for img_path in images_path:
        if os.path.isfile(img_path):
            image = Image.open(img_path)

            plt.subplot(2, 3, images_shown + 1)
            plt.imshow(image)
            plt.xticks([])
            plt.yticks([])

            images_shown += 1
            if images_shown >= 5:
                break

plot_images(img)

# !git clone https://github.com/run-llama/llama_index.git

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-genai

#import os, google.generativeai as genai

#os.environ["GOOGLE_API_KEY"] = "AIzaSyCpJogWwZX7en-xM9pKXNnT6IAfvot_Ku4"
#genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

#print("✅ API key set correctly!")

#print("Stored key:", os.environ.get("GOOGLE_API_KEY")[:10] + "********")  # only show first 10 chars

import os, google.generativeai as genai

client = genai # Use the configured genai object directly

models = client.list_models()
for m in models:
    print(m.name, "-", m.description)

import os
import google.generativeai as genai

# Make sure your API key is set
os.environ["GOOGLE_API_KEY"] = os.environ.get("GOOGLE_API_KEY", "YOUR_API_KEY_HERE")
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# Initialize Gemini model
model = genai.GenerativeModel(model_name="models/gemini-2.5-pro")

# Start a chat session
chat = model.start_chat(history=[])

# Send a test message
response = chat.send_message("Hello, Gemini!")
print("Gemini response:", response.text)

"""WE ARE TRYING TO INSTALL llama_index.llms.google_genai for google gemini api"""

#!pip uninstall -y llama-index

#!ls -la /content/llama_index/llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms


"""Check what’s inside the module"""


"""> module found
The correct class name inside the module is GoogleGenAI, not GoogleGemini or GoogleGenerativeAI.

"""


"""interface connectors between LlamaIndex (the data + reasoning layer) and the underlying LLM provider (OpenAI or Google).
In essence, they both:

Allow LlamaIndex to send prompts, embeddings, and multimodal data to the target LLM API

Receive structured responses (text, reasoning, multimodal content)

Integrate those results with indexes, retrievers, and RAG pipelines

"""

google_mm_llm = genai.GenerativeModel(
    model="models/gemini-2.5-pro",  # ✅ Best stable multimodal Gemini model
    api_key=os.environ.get("GOOGLE_API_KEY", "YOUR_API_KEY_HERE")
)

"""# QUESTION
**DO I NEED TO RUN
"`from llama_index.multi_modal_llms.generic_utils import load_image`"
 TO COMPELETE THE SAME FUNCTIONALITIES , AS
"`from llama_index.multi_modal_llms.openai import OpenAIMultiModal`"  SERVING
OR
"`from llama_index.llms.google_genai import GoogleGenAI`" WILL BE ENOUGH ?**

---
**The Relationship Between These Imports**

 1️⃣ from llama_index.llms.google_genai import GoogleGenAI

 → This imports the model interface (the brain).

It connects LlamaIndex → Google Gemini API, i.e. handles text and multimodal reasoning (if you feed it text, image, or both).

However, this class does not handle how images are loaded, processed, or converted before sending to Gemini.
It expects an image object (usually in PIL.Image or bytes format).

-----

2️⃣ from llama_index.multi_modal_llms.generic_utils import load_image

→ This imports a utility function (the hands).

It helps you load or preprocess image files into the correct format that Gemini or OpenAI models can understand when you call something like:



```
 response = llm.complete(prompt="Describe this image", image=load_image("dog.png"))

```
Without this helper, you would have to manually write:

```
from PIL import Image
image = Image.open("dog.png")
```

✅ In short: if your goal is image understanding with GoogleGenAI, you must use a function like `load_image`
"""

def load_image(path: str):
    return Image.open(path)

#prompt for query
qa_tmpl_str=(
    "Based on the provided information, including relevant images and retrieved context from the video, accurately and precisely answer the query without any additional prior knowledge.\n"
    "-----------------------\n"
    "Context: {context_str}\n" # Added context_str here
    "Metadata for video: {metadata_str} \n" # Escaped curly braces

    "-----------------------\n"

    "Query: {query_str}\n" # Escaped curly braces
    "Answer: "
)

img

#for converting metadata of video into json
import json
metadata_str=json.dumps(metadata_vid)

query_str="how important logarithms is for math ?  "

context_str = "".join(text)

image_docouments = SimpleDirectoryReader(input_files=img).load_data()

"""I've added `nest_asyncio` and applied the patch. Now you should be able to run the cell with the `llm.complete()` call without the `RuntimeError`."""

# Commented out IPython magic to ensure Python compatibility.
# %pip install nest_asyncio
import nest_asyncio
nest_asyncio.apply()

result = google_mm_llm.complete(
    prompt=qa_tmpl_str.format(
        query_str=query_str,
        metadata_str=metadata_str,
        context_str=context_str
    ),
    image=image_docouments
)

"""


>Note

---
Even if we remove `context_str` from `result` and `qa_tmpl_str` , our Retriever will **generate results** on the basis of *plot images*
"""

print(result.text)
